name: custom-build
on:
  push:
    branches:
    - 'custom-builds/**'


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 15
      matrix:
        include:
          - project: likecoin
            version: v2.0.2
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build
        run: |
          touch .env # Create dummy env file
          cd ${{matrix.project}}
          docker buildx bake -f build.yml --set node_1.tags=ghcr.io/${{ github.repository }}:b${{ github.run_number }}-${{matrix.project}}-${{matrix.version}}${{matrix.tag_suffix}} --push
