name: custom-build
on:
  push:
    branches:
    - 'custom-builds/**'


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 15
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: PrepareReg Names
        # Container repo cannot have uppercase chars
        #
        # Ref
        # https://github.com/docker/build-push-action/issues/37#issuecomment-720358308
        run: |
          echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
          echo IMAGE_TAG=$(echo ${{ github.ref }} | tr '[:upper:]' '[:lower:]' | awk '{split($0,a,"/"); print a[3]}') >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          # Reference
          # https://github.com/docker/login-action#github-container-registry
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
          touch .env # Create dummy env file
          cd generic
          docker buildx bake -f build.yml --set node_1.tags=ghcr.io/${{ env.IMAGE_REPOSITORY }}:b${{ github.run_number }}-generic --push
